"""`mame-curator setup` subcommand handler."""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml
from rich.console import Console
from rich.prompt import Prompt

_SETUP_HEADER = """\
# MAME Curator configuration.
# Generated by `mame-curator setup`. Edit by hand or via the in-app
# Settings page. See config.example.yaml in the repo for a fully-commented
# template covering every section (filters, picker, ui, updates, …).
# Sections omitted here fall back to AppConfig defaults.

"""


def _prompt_path(label: str, supplied: Path | None) -> Path:
    """Return a Path either from the supplied flag value or via prompt.

    Empty / whitespace-only input re-prompts. Tilde expansion is applied so
    users can type ``~/Games/MAME`` without surprise.
    """
    if supplied is not None:
        return supplied
    while True:
        raw = Prompt.ask(label).strip()
        if raw:
            return Path(raw).expanduser()


def _cmd_setup(args: argparse.Namespace) -> int:
    console = Console()
    err_console = Console(stderr=True, soft_wrap=True)

    if args.out.exists() and not args.force:
        err_console.print(
            f"[red]error:[/red] {args.out!r} already exists — pass --force to overwrite."
        )
        return 1

    console.print("[bold]MAME Curator setup[/bold] — writes a starter config.yaml.")
    console.print("Press Enter after each path. Tilde (~) is expanded.\n")

    source_roms = _prompt_path("Source ROM directory (non-merged)", args.source_roms)
    source_dat = _prompt_path("Source DAT file (.xml or .zip)", args.source_dat)
    dest_roms = _prompt_path("Destination ROM directory", args.dest_roms)
    retroarch_playlist = _prompt_path(
        "RetroArch playlist target (e.g. <dest>/mame.lpl)", args.retroarch_playlist
    )

    if not source_roms.is_dir():
        err_console.print(
            f"[red]error:[/red] source_roms {str(source_roms)!r} "
            "does not exist or is not a directory."
        )
        return 1
    if not source_dat.is_file():
        err_console.print(
            f"[red]error:[/red] source_dat {str(source_dat)!r} does not exist or is not a file."
        )
        return 1

    paths_block = {
        "paths": {
            "source_roms": str(source_roms),
            "source_dat": str(source_dat),
            "dest_roms": str(dest_roms),
            "retroarch_playlist": str(retroarch_playlist),
        }
    }
    body = _SETUP_HEADER + yaml.safe_dump(paths_block, sort_keys=False)

    try:
        args.out.write_text(body, encoding="utf-8")
    except OSError as exc:
        err_console.print(f"[red]error:[/red] failed to write {args.out!r}: {exc}")
        return 1

    console.print(f"\n[green]✓[/green] wrote {args.out}")
    console.print(
        "Run [bold]mame-curator serve --config "
        f"{args.out}[/bold] (or [bold]./scripts/dev.sh[/bold]) to start the app."
    )
    return 0
